### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by nuomiaa** [w4rum/squadlanes#42]
poetry install
How should it be installed on Windows systems?
```    [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
    ERROR: Failed building wheel for typed-ast
  Failed to build typed-ast
  ERROR: Could not build wheels for typed-ast, which is required to install pyproject.toml-based projects


  at ~\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\utils\env.py:1476 in _run
      1472│                 output = subprocess.check_output(
      1473│                     command, stderr=subprocess.STDOUT, env=env, **kwargs
      1474│                 )
      1475│         except CalledProcessError as e:
    → 1476│             raise EnvCommandError(e, input=input_)
      1477│
      1478│         return decode(output)
      1479│
      1480│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:

The following error occurred when trying to handle this error:


  PoetryException

  Failed to install C:/Users/NuoMi/AppData/Local/pypoetry/Cache/artifacts/cc/50/4d/e1b50dadd10f8d3f8bd6f6c2e764cf988f0e86c4047c0210353ba77680/typed_ast-1.4.3.tar.gz

  at ~\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\utils\pip.py:51 in pip_install
       47│
       48│     try:
       49│         return environment.run_pip(*args)
       50│     except EnvCommandError as e:
    →  51│         raise PoetryException(f"Failed to install {path.as_posix()}") from e
       52│```

**Comment by grey275** [comment]
Maybe there are other good suggestions, but your best bet is probably to just use Windows Subsystem for Linux(ubuntu should be fine): https://learn.microsoft.com/en-us/windows/wsl/install

**Comment by w4rum** [comment]
@nuomiaa 
> How should it be installed on Windows systems?

Installing on Windows is not supported. I'm not too familiar with using Poetry on Windows and I can't immediately make out what's causing your issue, so I'm afraid you're on your own with this.

Using WSL instead of trying to run it natively, as @grey275 suggested, will probably get you part of the way. But you'll still have to get the rest (Docker, Wine, and my UEViewer fork) to work. Others have attempted to port this project to Windows (including #30). Unfortunately, I have so far not found the time to help with those attempts or bring the project into a more portable state. 

I have to admit, as well, that that's quite low on my priority list and will probably not be worked on by me in the foreseeable future. I'll close this issue. Feel free to keep discussing in here, open a PR if you've found a solution, or contribute to #30.

**Comment by w4rum** [comment]
Note: If you're only interested in working on the website and don't need to run the datamining scripts yourself, you can always find the current `raas-data.yaml` [here](https://github.com/w4rum/squadlanes/blob/master/src/assets/raas-data.yaml).

**Comment by nuomiaa** [comment]
> Note: If you're only interested in working on the website and don't need to run the datamining scripts yourself, you can always find the current `raas-data.yaml` [here](https://github.com/w4rum/squadlanes/blob/master/src/assets/raas-data.yaml).

@w4rum I can't find the map image data.
