### ISSUE TITLE
Vehicle spawn information

### ISSUE THREAD

**Issue by Lenart12** [w4rum/squadlanes#9]
Would be usefull to display vehicles and spawn delays for the selected layer

**Comment by w4rum** [comment]
We actually had a rather extensive UI mapped out that contained, among other things, vehicle information. I never got around to implement teh UI or automatic extraction of vehicle information though. And since I haven't played Squad in quite a while, I doubt I'll get to that in the near future.

So I'll have to put this feature request on ice for now, sorry.

**Comment by w4rum** [comment]
Closing to empty out the log.
